In [1]:
#Multiple Regression
#Importing the libraries
import numpy as np  
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('reklam.csv')
data.head()

sıra     TV  radyo  gazete  satış
0     1  230.1   37.8    69.2   22.1
1     2   44.5   39.3    45.1   10.4
2     3   17.2   45.9    69.3    9.3
3     4  151.5   41.3    58.5   18.5
4     5  180.8   10.8    58.4   12.9

In [3]:
x = data.iloc[:,1:-1].values #bağımsız değişkenler (TV,radio,gazete)


In [5]:
y =data.iloc[:,-1].values.reshape(-1,1) #bağımlı değişken (satışlar)

In [6]:
x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [7]:
y

array([[22.1],
       [10.4],
       [ 9.3],
       [18.5],
       [12.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [10.6],
       [ 8.6],
       [17.4],
       [ 9.2],
       [ 9.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [12.5],
       [ 5.6],
       [15.5],
       [ 9.7],
       [12. ],
       [15. ],
       [15.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [ 9.6],
       [17.4],
       [ 9.5],
       [12.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [12.9],
       [ 8.5],
       [14.9],
       [10.6],
       [23.2],
       [14.8],
       [ 9.7],
       [11.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [15.7],
       [14. ],
       [18. ],
       [ 9.3],
       [ 9

In [8]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state = 22)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [10]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [11]:
yhead = lr.predict(xtest)   #yhead = ypredict tahmin edilen y değerleri
yhead

array([[10.13196686],
       [ 9.85056624],
       [ 7.56478088],
       [24.09139679],
       [17.40839719],
       [ 9.06049066],
       [ 4.53051589],
       [ 7.45074654],
       [19.47769535],
       [12.31170493],
       [ 6.166006  ],
       [19.87745111],
       [20.22291383],
       [18.07510828],
       [15.84266134],
       [ 8.88226018],
       [22.31162026],
       [23.35516667],
       [14.31073638],
       [10.92023904],
       [16.56183236],
       [19.18374909],
       [19.23908822],
       [14.15149454],
       [12.42077227],
       [14.91633971],
       [ 9.81364486],
       [11.12877659],
       [17.35372639],
       [21.48475253],
       [13.78896023],
       [17.78317687],
       [ 9.17311761],
       [10.3989317 ],
       [ 8.41659611],
       [ 8.76335744],
       [17.13446926],
       [18.33607871],
       [11.9410246 ],
       [10.72809865],
       [22.91468826],
       [ 9.97928162],
       [11.3805303 ],
       [18.11905172],
       [12.54305398],
       [15

In [12]:
lr.predict([[30,40,50]])

array([[12.14784155]])

In [13]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(ytest,yhead))

r2= r2_score(ytest,yhead)

print('rmse değeri:',rmse)
print('r2 değeri:',r2)

rmse değeri: 1.592659147354783
r2 değeri: 0.904888739398882


In [16]:
def calculate_rmse(predictions, targets):
    """
    Calculates the Root Mean Squared Error (RMSE) between the predicted values and the target values.

    Args:
        predictions (list): A list of predicted values.
        targets (list): A list of target values.

    Returns:
        float: The RMSE value.
    """
    # Calculate the squared differences between predictions and targets
    squared_diff = [(p - t) ** 2 for p, t in zip(predictions, targets)]

    # Calculate the mean squared difference
    mean_squared_diff = sum(squared_diff) / len(predictions)

    # Calculate the RMSE by taking the square root of the mean squared difference
    rmse = mean_squared_diff ** 0.5

    return rmse


In [17]:
print(calculate_rmse(yhead,ytest))

[1.59265915]
